# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'viewCode' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Nimble'
  pod 'SnapKit', '~> 5.0.0'

  
    target "viewCodeUITests" do
    inherit! :search_paths

    pod 'SnapKit', '~> 5.0.0'
    pod 'Nimble'
    pod 'Nimble-Snapshots'
    pod 'Quick'

  end

end
